Delete unnecessary condition
Covscan log:

Error: REVERSE_INULL (CWE-476):
mariadb-connector-c-3.1.6-src/libmariadb/mariadb_lib.c:2166: deref_ptr: Directly dereferencing pointer "mysql".
mariadb-connector-c-3.1.6-src/libmariadb/mariadb_lib.c:2171: check_after_deref: Null-checking "mysql" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.