CONC-786: ma_open under HAVE_REMOTEIO reads from uninitialized mysql struct
Infer error is:

libmariadb/ma_io.c:126: error: Uninitialized Value(PULSE_UNINITIALIZED_VALUE)
  `mysql.options.extension` is read without initialization during the call to `mysql_client_find_plugin()`.
  124.     MYSQL mysql;
  125.     if (rio_plugin ||(rio_plugin= (struct st_mysql_client_plugin_REMOTEIO *)
  126.                       mysql_client_find_plugin(&mysql, NULL, MARIADB_CLIENT_REMOTEIO_PLUGIN)))

The mysql structure here is obsecuring the 'mysql' pointer passed to the
function. The mysql_client_find_plugin uses the mysql.options.extension
in mysql_load_plugin_v to determine if a path or environment variable
is used to load the plugin. As the mysql pointer passed in is assumed to
have been initialized.

This wasn't the case with mariadb_rpl_open where the implementation
adds a mysql_init, and closes it before returning.