CONC-786: mariadb_reconnect mysql_init failure requires no mysql_close
With the previous commit, a mysql_init failure leaves no memory
allocated, so there's no need to close.

This avoids a Infer error (but I didn't see the cause):

libmariadb/mariadb_lib.c:2108: error: Uninitialized Value(PULSE_UNINITIALIZED_VALUE)
  `mysql.extension` is read without initialization during the call to `mysql_close()`.
    MYSQL tmp_mysql;
   if (!mysql_init(&tmp_mysql))
    {
      /* extensions may have failed to allocate */
      SET_CLIENT_ERROR(mysql, CR_OUT_OF_MEMORY, SQLSTATE_UNKNOWN, 0);
  2106.     tmp_mysql.free_me= 0;
  2107.     mysql_close(&tmp_mysql);
  2108.     return(1);