CONC-786: dyncol: hdr.offset is read without initialization
The init_read_hdr static function is called from 3
locations within this file for a hdr on the stack.
This was the logical location to initialize offset.

Infer error:

libmariadb/mariadb_dyncol.c:4145: error: Uninitialized Value(PULSE_UNINITIALIZED_VALUE)
  `hdr.offset` is read without initialization during the call to `hdr_interval_length()`.
  4143.       goto err;
  4144.     header.length=
  4145.       hdr_interval_length(&header, header.entry + header.entry_size);
              ^
  4146.     header.data= header.dtpool + header.offset;
  4147.     /*